# Playbook for the cloud deployment. Ordering is important as a deployment is sequential. 

- hosts: nc
  sudo: yes
  vars_files:
    - vars/main.yml
  roles:
    - common
    - nodes

- hosts: cc
  vars_files:
    - vars/main.yml
  sudo: yes
  roles:
    - common
    - cc
    
- hosts: sc
  vars_files:
    - vars/main.yml
  sudo: yes
  roles:
    - common
    - sc

- hosts: walrus
  sudo: yes
  vars_files:
    - vars/main.yml
  roles:
    - common
    - walrus
 
- hosts: clc
  vars_files:
    - vars/main.yml
  sudo: yes
  roles:
    - common
    - clc
