# Playbook for the cloud deployment.

- hosts: nc
  sudo: yes
  vars_files:
    - vars/main.yml
  roles:
    - common
    - nodes

- hosts: walrus
  sudo: yes
  vars_files:
    - vars/main.yml
  roles:
    - common
    - walrus
    
- hosts: cc
  vars_files:
    - vars/main.yml
  sudo: yes
  roles:
    - common
    - cc
    
- hosts: sc
  vars_files:
    - vars/main.yml
  sudo: yes
  roles:
    - common
    - sc
 
- hosts: clc
  vars_files:
    - vars/main.yml
  sudo: yes
  roles:
    - common
    - clc 
