    - name: set tuned profile
      action: command tuned-adm profile enterprise-storage

    - name: Install the NC packages
      action: yum name=eucalyptus-nc state=present

    - name: Template the configuration file
      action: template src=../../common/templates/eucalyptus.conf.j2 dest=/etc/eucalyptus.conf
                
